development: &non_production_settings
  site_url: localhost:3000
  site_name: flexpaper
  admin_email: yueyuegigi21@gmail.com
  default_password: aaaaaaaa
  
test:
  <<: *non_production_settings


production:
  site_url: http://www.example.com
  site_name: yueyuegigi21
  admin_email: yueyuegigi21@gmail.com
